### ISSUE TITLE
Dropped items not removed when spawn-reason is enabled

### ISSUE THREAD

**Issue by rmalca** [SilverstoneMC/EntityClearer#11]
### Description of the bug

Ground items are not removed when spawn-reason.enabled = true.

I think DROPPED_ITEM should ignore the spawn-reason or create an option similar to the following:

```
worlds:
  ALL:
    dropped-items: true # not recommended, you should use Paper's alternate item despawn rates instead!
    entities:
      - ZOMBIE
    spawn-reason:
      enabled: true
      reasons:
        - SPAWNER
```

### Link to latest.log file with print-stack-traces enabled

https://paste.gg/p/anonymous/91cc1a130e60466ca8efcd59ab59a9a1

### Steps to reproduce the problem

1. Use /clearentities.

### Expected behavior

DROPPED_ITEM should ignore the spawn-reason

### Output of `/version`

git-Purpur-"4ff0630" (MC: 1.17.1)

### Output of `/version EntityClearer`

1.10.4-beta

### EntityClearer config.yml

```yaml
# This config was generated for version 1.10.1
# Find the latest config at https://github.com/JasonHorkles/EntityClearer/blob/main/config.yml

# This plugin uses bStats metrics
# https://bstats.org/plugin/bukkit/EntityClearer/10915
# Metrics can be disabled in the bStats config.yml

# Interval in minutes the clear task should run
# To disable the timer, set the interval to 0 (useful if only using TPS monitoring)
interval: 5

# The sound to play when showing the warnings
# See https://minecraft.fandom.com/wiki/Sounds.json#Java_Edition_values for all sounds
# Set to '' for no sound
sound: 'ui.button.click'

# The worlds to check and remove entities from
# Make sure to add your world(s) if they're not already there
# See https://papermc.io/javadocs/paper/1.17/org/bukkit/entity/EntityType.html for all entities
# Note: You should not be using DROPPED_ITEM in your list as you should use Paper's alternate item despawn rates instead!
worlds:
  ALL: # <- Change this to be whatever world name you'd like, or set it to ALL to apply to all worlds
    # The entities to be removed from the world
    entities:
      - DROPPED_ITEM
    # Should only entities with a specific spawn reason be removed?
    # Setting this to false will check for any spawn reason
    spawn-reason:
      enabled: false
      # See https://papermc.io/javadocs/paper/1.17/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html for all spawn reasons
      reasons: []
  world:
    entities:
      - PIG
      - SHEEP
      - CHICKEN
      - COW
      - MUSHROOM_COW
      - ZOMBIE
      - SPIDER
      - CAVE_SPIDER
      - SKELETON
      - BLAZE
      - MAGMA_CUBE
      - BEE
      - IRON_GOLEM
      - CREEPER
    spawn-reason:
      enabled: true
      reasons:
        - SPAWNER
  world_nether:
    entities:
      - PIG
      - SHEEP
      - CHICKEN
      - COW
      - MUSHROOM_COW
      - ZOMBIE
      - SPIDER
      - CAVE_SPIDER
      - SKELETON
      - BLAZE
      - MAGMA_CUBE
      - BEE
      - IRON_GOLEM
      - CREEPER
    spawn-reason:
      enabled: true
      reasons:
        - SPAWNER
  world_the_end:
    entities:
      - PIG
      - SHEEP
      - CHICKEN
      - COW
      - MUSHROOM_COW
      - ZOMBIE
      - SPIDER
      - CAVE_SPIDER
      - SKELETON
      - BLAZE
      - MAGMA_CUBE
      - BEE
      - IRON_GOLEM
      - CREEPER
    spawn-reason:
      enabled: true
      reasons:
        - SPAWNER

nearby-entities:
  # Should the plugin only remove entities that have multiple entities nearby?
  # This is useful to only remove large groups of entities while leaving smaller entity groups alone
  # Using this would prevent every entity from being removed then just respawning again naturally
  # It is recommended to leave this feature enabled
  enabled: true
  # Only apply to worlds with the mob spawning gamerule enabled?
  gamerule-enabled-only: false
  # The distance in blocks that the plugin should check for extra entities
  x: 48
  y: 48
  z: 48
  # How many additional entities must be around the first entity to be removed?
  count: 4

# Should using the command /clearentities start the countdown or instantly remove the entities?
countdown-on-command: false

# Should named entities be removed?
remove-named: false

messages:
  # Should there be action bar messages?
  actionbar: false
  # Should there be chat messages?
  chat: true
  # This plugin supports MiniMessage markdown and formatting - see https://docs.adventure.kyori.net/minimessage.html#format
  actionbar-message: "<#ff9b0f>&lObjetos del suelo se eliminarán en &e&l{SECONDS} <#ff9b0f>&lseg"
  actionbar-completed-message: "<#ff9b0f>&lObjetos del suelo eliminados: &e&l{ENTITIES}"
  actionbar-completed-low-tps-message: "<#ff9b0f>&lObjetos del suelo eliminados: &e&l{ENTITIES}"
  chat-message: "&cLos objetos del suelo se eliminarán en &e{SECONDS} &6seg&c."
  chat-completed-message: "&aObjetos del suelo eliminados: &e{ENTITIES}"
  chat-completed-low-tps-message: "&aObjetos del suelo eliminados: &e{ENTITIES}"

# When should the warning messages send?
# Time is in seconds remaining before the clear task
warning-messages:
  60-seconds: true
  45-seconds: false
  30-seconds: false
  15-seconds: true
  5-seconds: false
  4-seconds: true
  3-seconds: true
  2-seconds: true
  1-second: true

# The command(s) to run after the entity clearing task runs
commands:
#  - nuke

low-tps:
  # Should the entity removal task be triggered when the TPS is low?
  enabled: false
  # Below what TPS should the plugin remove the entities?
  threshold: 17
  # Should there be a chat message sent to players with the `entityclearer.lowtps`
  # permission stating that the TPS is low?
  chat: true
  chat-message: "&c&lWarning: TPS low &8&l(&7&l{TPS}&8&l)&c&l! Removing entities..."

  # Should the list of entities to remove be separate from the one defined above?
  separate-entity-list: false
  # This list will not be active unless the above option is true
  worlds:
    your_world_name: # <- Change this to be whatever world name you'd like, or set it to ALL to apply to all worlds
      entities:
        - BEE
        - ARMOR_STAND
        - ARROW
        - BOAT
        - CAVE_SPIDER
        - CHICKEN
        - CREEPER
        - FALLING_BLOCK
        - MINECART
        - MINECART_CHEST
        - MINECART_FURNACE
        - MINECART_HOPPER
        - MINECART_TNT
        - SHEEP
        - SKELETON
        - SLIME
        - SPIDER
        - SQUID
        - WOLF
        - ZOMBIE
      spawn-reason:
        enabled: false
        reasons: [ ]
    your_world_name_nether: # <- Change this to be whatever world name you'd like
      entities:
        - BLAZE
        - ARMOR_STAND
        - ARROW
        - BOAT
        - FALLING_BLOCK
        - MINECART
        - MINECART_CHEST
        - MINECART_FURNACE
        - MINECART_HOPPER
        - MINECART_TNT
        - ZOMBIFIED_PIGLIN
      spawn-reason:
        enabled: false
        reasons: [ ]

###############################################

# Debug stuff
# You shouldn't need to touch this unless specifically asked to do so :)
print-stack-traces: true
debug: true
```
