### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by BugPatcher** [SilverstoneMC/EntityClearer#15]
### Description of the bug

It gives me a certain error message whenever i use the command.

### Steps to reproduce the problem

Enter the clearentity command

### Expected behavior

It clears entities.

### Output of `/version`

[09:51:37] [Server thread/INFO]: This server is running CraftBukkit version 3513-Spigot-fa893f0-576a037 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)
[09:51:37] [Server thread/INFO]: Checking version, please wait...
[09:51:37] [Thread-18/INFO]: You are running the latest version

### Output of `/version EntityClearer`

>version entityclearer
[09:53:51] [Server thread/INFO]: EntityClearer version 1.12.1
[09:53:51] [Server thread/INFO]: Remove entities from your worlds!
[09:53:51] [Server thread/INFO]: Website: https://github.com/SilverstoneMC/EntityClearer
[09:53:51] [Server thread/INFO]: Author: JasonHorkles
>

### EntityClearer config.yml

```yaml
# This config was generated for version 1.12.1
# Find the latest config at https://github.com/SilverstoneMC/EntityClearer/blob/main/src/main/resources/config.yml

# This plugin uses bStats metrics
# https://bstats.org/plugin/bukkit/EntityClearer/10915
# Metrics can be disabled in the bStats config.yml

# Interval in minutes the clear task should run
# To disable the timer, set the interval to 0 (useful if only using TPS monitoring)
interval: 0

# The sound to play when showing the warnings
# See https://minecraft.fandom.com/wiki/Sounds.json#:~:text=be%20found%20here.-,Sound%20events,-A%20sound%20event for all sounds
# Set to '' for no sound
sound: ''

# The sound's pitch played when the timer is counting down
# Valid values are between 0.0-2.0
countdown-pitch: 0.9

# The sound's pitch played when the entites are cleared
# Valid values are between 0.0-2.0
cleared-pitch: 1.0

# The worlds to check and remove entities from
# Make sure to add your world(s) if they're not already there
# See https://papermc.io/javadocs/paper/1.18/org/bukkit/entity/EntityType.html for all entities
# Note: You should not be using DROPPED_ITEM in your list as you should use Paper's alternate item despawn rates instead!
worlds:
  ALL: # <- Change your_world_name to be whatever world name you'd like, or set it to ALL to apply to all worlds (ALL overrides any other worlds below)
    # The entities to be removed from the world
    entities:
      - BEE
      - CAVE_SPIDER
      - CHICKEN
      - CREEPER
      - SHEEP
      - SKELETON
      - SLIME
      - SPIDER
      - SQUID
      - WOLF
      - ZOMBIE
    # Should only entities with a specific spawn reason be removed?
    # Setting this to false will check for any spawn reason
    spawn-reason:
      enabled: true
      # See https://papermc.io/javadocs/paper/1.18/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html for all spawn reasons
      reasons:
        - SPAWNER
        - SPAWNER_EGG
  your_world_name_nether: # <- Change your_world_name_nether to be whatever world name you'd like
    entities:
      - BLAZE
      - ZOMBIFIED_PIGLIN
    spawn-reason:
      enabled: false
      reasons: [ ]
#  creative:
#    entities:
#      - ARMOR_STAND
#      - ARROW
#      - BOAT
#      - DROPPED_ITEM
#      - MINECART
#      - MINECART_CHEST
#      - MINECART_FURNACE
#      - MINECART_HOPPER
#      - MINECART_TNT
#    spawn-reason:
#      enabled: false
#      reasons: [ ]

nearby-entities:
  # Should the plugin only remove entities that have multiple entities nearby?
  # This is useful to only remove large groups of entities while leaving smaller entity groups alone
  # Using this would prevent every entity from being removed then just respawning again naturally
  # It is recommended to leave this feature enabled
  enabled: true
  # Should the plugin only count nearby entities that are also on the remove list?
  # Setting this to false will count ANY nearby entity, including players, XP Orbs, Item Frames, etc
  only-count-from-list: true
  # The distance in blocks that the plugin should check for extra entities
  x: 3
  y: 3
  z: 3
  # How many additional entities must be around the first entity to be removed?
  count: 14

# Should using the command /clearentities start the countdown or instantly remove the entities?
countdown-on-command: false

# Should named entities be removed?
remove-named: false

messages:
  # Set the message to "" to disable it
  # This plugin supports MiniMessage markdown and formatting - see https://docs.adventure.kyori.net/minimessage.html#format
  
  # Placeholders:
  # {SECONDS} - the time remaining before the clear task is run
  # {S} - if the seconds remaining is above 1, an `s` will be appended
  # {ENTITIES} - the amount of entities removed after the clear task has run
  
  actionbar-message: "<#ff9b0f>&lCommon entities will be removed in &e&l{SECONDS} <#ff9b0f>&lsecond{S}!"
  actionbar-completed-message: "<#ff9b0f>&lRemoved &e&l{ENTITIES} <#ff9b0f>&lentities!"
  actionbar-completed-low-tps-message: "<#ff9b0f>&lRemoved &e&l{ENTITIES} <#ff9b0f>&lentities due to low TPS!"
  chat-message: "&cCommon entities will be removed in &7{SECONDS} &csecond{S}!"
  chat-completed-message: "&cRemoved &7{ENTITIES} &centities!"
  chat-completed-low-tps-message: "&cRemoved &7{ENTITIES} &centities due to low TPS!"

# When should the warning messages send?
# Time is in seconds remaining before the clear task
warning-messages:
  60-seconds: false
  45-seconds: false
  30-seconds: true
  15-seconds: false
  5-seconds: true
  4-seconds: true
  3-seconds: true
  2-seconds: true
  1-second: true

# The command(s) to run after the entity clearing task runs
commands:
#  - nuke

low-tps:
  # Should the entity removal task be triggered when the TPS is low?
  enabled: true
  # Below what TPS should the plugin remove the entities?
  threshold: 17
  # Should there be a chat message sent to players with the `entityclearer.lowtps`
  # permission stating that the TPS is low?
  chat: true
  # Placeholders:
  # {TPS} - the current TPS of the server
  chat-message: "&c&lWarning: TPS low &8&l(&7&l{TPS}&8&l)&c&l! Removing entities..."

  # Should the list of entities to remove be separate from the one defined above?
  separate-entity-list: false
  # This list will not be active unless the above option is true
  worlds:
    ALL: # <- Change your_world_name to be whatever world name you'd like, or set it to ALL to apply to all worlds (ALL overrides any other worlds below)
      entities:
        - BEE
        - ARMOR_STAND
        - ARROW
        - BOAT
        - CAVE_SPIDER
        - CHICKEN
        - CREEPER
        - FALLING_BLOCK
        - MINECART
        - MINECART_CHEST
        - MINECART_FURNACE
        - MINECART_HOPPER
        - MINECART_TNT
        - SHEEP
        - SKELETON
        - SLIME
        - SPIDER
        - SQUID
        - WOLF
        - ZOMBIE
      spawn-reason:
        enabled: true
        reasons: [natural, spawner]
    your_world_name_nether: # <- Change your_world_name_nether to be whatever world name you'd like
      entities:
        - BLAZE
        - ARMOR_STAND
        - ARROW
        - BOAT
        - FALLING_BLOCK
        - MINECART
        - MINECART_CHEST
        - MINECART_FURNACE
        - MINECART_HOPPER
        - MINECART_TNT
        - ZOMBIFIED_PIGLIN
      spawn-reason:
        enabled: false
        reasons: [ ]

###############################################

# Debug stuff
# You shouldn't need to touch this unless specifically asked to do so :)
print-stack-traces: false
```

### Debug file

[debug-1654786486733.txt](https://github.com/SilverstoneMC/EntityClearer/files/8871518/debug-1654786486733.txt)
